site_name: MolBase Documentation
theme:
  name: material
  palette:
    scheme: slate  # dark mode default
nav:
  - Home: index.md
  - Features: features.md
  - Architecture: architecture.md
  - Setup: setup.md
